name: MacOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependency
      run: |
        brew install automake

    - name: make
      run: |
        autoreconf -i
        ./configure
        make

    - name: test
      run: |
        cd test
        make
        find . -name *.bin -exec '{}' --success ';'
