name: MacOS

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependency
      run: |
        brew install automake

    - name: make
      run: |
        autoreconf -i
        ./configure
        make

    - name: test
      run: |
        cd test
        make
        ./bcf-reader.bin
        ./bcf-writer.bin
        ./bam-reader.bin
        # find . -name "*.bin" -exec '{}' --success ';'
